import{a as w,S as h,i as p}from"./assets/vendor-5401a4b0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const o of e.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&n(o)}).observe(document,{childList:!0,subtree:!0});function a(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function n(t){if(t.ep)return;t.ep=!0;const e=a(t);fetch(t.href,e)}})();async function g(s,r,a){try{return(await w.get(`https://pixabay.com/api/?key=42390254-a1d01e86edd47d7ed3c2f6c78&q=${s}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${a}`)).data}catch(n){throw console.error("Error fetching data:",n),n}}function y(s){return s.hits.map(r=>`<li class="gallery-item"><a href="${r.webformatURL}">
            <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}"></a>
            <div class='comments'>
            <p><b>Likes: </b>${r.likes}</p>
            <p><b>Views: </b>${r.views}</p>
            <p><b>Comments: </b>${r.comments}</p>
            <p><b>Downloads: </b>${r.downloads}</p>
            </div>
            </li>`).join("")}const v=document.querySelector("#form"),d=document.querySelector(".loader"),m=document.querySelector(".gallery"),u=document.querySelector(".load-btn");let i,f=15,c="",l;const b={captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",animation:250,widthRatio:.9,scaleImageToRatio:!0};document.addEventListener("DOMContentLoaded",()=>{v.addEventListener("submit",async e=>{if(e.preventDefault(),c=document.getElementById("search").value.trim(),!c||c===" ")return n("The search field should not be empty");i=1,d.classList.remove("hidden"),u.classList.remove("hidden"),m.innerHTML="";try{const o=await g(c,i,f);t(o);const L=y(o);m.insertAdjacentHTML("beforeend",L),l=new h(".gallery a",b),l.refresh()}catch(o){console.error("Error fetching data:",o)}finally{d.classList.add("hidden")}}),u.addEventListener("click",s);async function s(){i+=1,d.classList.remove("hidden");try{const e=await g(c,i,f);t(e);const o=y(e);l.destroy(),m.insertAdjacentHTML("beforeend",o),l=new h(".gallery a",b),l.refresh(),a(),i*f>=e.totalHits&&r()}catch(e){console.error("Error fetching data:",e)}finally{d.classList.add("hidden")}}function r(){u.classList.add("hidden"),n("We're sorry, but you've reached the end of search results.")}function a(){const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}function n(e){p.error({title:"",backgroundColor:"#EF4040",message:e,position:"topRight"})}function t(e){e.hits.length===0&&(u.classList.add("hidden"),p.error({title:"",backgroundColor:"#EF4040",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}))}});
//# sourceMappingURL=commonHelpers.js.map
